services:
  uzte-web:
    container_name: uzte-web
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uzte-app
    networks:
      - uzte-network

  uzte-app:
    container_name: uzte-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - uzte-db
    volumes:
      - ./:/var/www
    networks:
      - uzte-network

  uzte-db:
    container_name: uzte-db
    image: mysql:8.0
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - uzte_mysql_data:/var/lib/mysql
    networks:
      - uzte-network

  uzte-pma:
    container_name: uzte-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: uzte-db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - uzte-db
    ports:
      - "9000:80"
    networks:
      - uzte-network

networks:
  uzte-network:
    driver: bridge

volumes:
  uzte_mysql_data: